version: '3.3'

volumes:
  pg_data_volume:
  static_volume:
  media_volume:

services:

  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_volume:/var/lib/postgresql/data

  backend:
    image: goaho7/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_volume:/app/static_backend/
      - media_volume:/app/media_backend/

  frontend:
    image: goaho7/foodgram_frontend
    depends_on:
      - db
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/var/html/static_backend/
      - media_volume:/var/html/media_backend/
